const upgradeDatas = [
  {
    title: "Basic",
    description: "For casual listening and discovering new music.",
    price: "₩ 0",
    features1: "Standard audio quality",
    features2: "Limited skips",
    features3: "Online streaming only",
    includes1: "Unlimited playlists",
    includes2: "Basic recommendations",
    includes3: "Cross-device sync",
  },
  {
    title: "Plus",
    description: "For listeners who want fewer interruptions.",
    price: "₩ 5,900",
    features1: "Fewer ads",
    features2: "Improved audio quality",
    features3: "More skips",
    includes1: "Enhanced recommendations",
    includes2: "Queue control",
    includes3: "Lyrics preview",
  },
  {
    title: "Premium",
    description: "For uninterrupted, high-quality listening.",
    price: "₩ 9,900",
    features1: "High quality audio",
    features2: "Unlimited skips",
    features3: "Background play",
    includes1: "Full lyrics",
    includes2: "Offline listening",
    includes3: "Smart mixes",
  },
  {
    title: "Pro",
    description: "For power listeners and creators.",
    price: "₩ 14,900",
    features1: "All Premium features",
    features2: "Lossless audio",
    features3: "Multi-device access",
    includes1: "Early access to new features",
    includes2: "Advanced audio settings",
    includes3: "Priority support",
  },
];